services: 
  db: 
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
    volumes: 
      - "./data/db:/var/lib/postgresql/data"
  web: 
    build: "."
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
    ports: 
      - "8000:8000"
    volumes: 
      - ".:/code"
version: "3.9"
